FROM svizor/zoomcamp-model:mlops-3.10.0-slim

RUN pip install -U pip
RUN pip install pipenv

WORKDIR /app

COPY [ "Pipfile", "Pipfile.lock", "./" ]

RUN pipenv install --system --deploy

COPY [ "starter-predict.py",  "./" ]

#COPY [ "model2.bin", "model.bin" ]


ENTRYPOINT ["python",  "starter-predict.py"]

CMD [ "0", "0" ]